### ISSUE TITLE
how "redis" help's python-concurrency? and other requirements too?

### ISSUE THREAD

**Issue by jknaresh** [volker48/python-concurrency#1]
Help me to understand.
I couldn't get , is any advantages are there to install requirements.txt file?
aiohttp==0.14.4
click==3.3
greenlet==0.4.5
redis==2.10.3
rq==0.5.0

Thank you.

-
Naresh

**Comment by volker48** [comment]
Some of the examples use code that is not included in the standard Python library. That is the reason for the requirements.
